"use strict";
var readlineSync = require('readline-sync');
console.log('welcome to my calculator');
// let str:string = readlineSync.question("what's your name?");
// let n :number = readlineSync.questionInt('enter a number');
// console.log(n);
// let b:number = n + 1
// console.log(b);     
var n1 = readlineSync.questionInt('enter the first number ');
var n2 = readlineSync.questionInt('enter the second number ');
var sum = n1 + n2;
var mult = n1 * n2;
var diff = n1 - n2;
var div = n1 / n2;
var qt = n1 % n2;
console.log("sum = " + sum);
console.log("mult = " + mult);
console.log("diff = " + diff);
console.log("div = " + div);
console.log("qt = " + qt);
console.log('bye');
